echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "I am learning branching in git and github"
echo "i am performing practicals git Branching concept"
echo "I am learning Git"
